# pandas - "A melhor biblioteca do Python para Dados"

- Quase sempre que você for trabalhar com dados no Python você vai usar o pandas, então é importante você saber trabalhar com essa biblioteca muito bem

- Vamos aprender os principais comandos e os princípios básicos do pandas

- Faça o download do Gabarito desse arquivo e use como uma cartilha de consulta (Link na descrição)

### Importando o pandas

In [1]:
import pandas as pd
pd.options.display.float_format = '{:.2f}'.format

### Criando um dataframe a partir de um dicionário

In [2]:
# dataframe = pd.DataFrame()
venda = {'data': ['15/02/2021', '16/02/2021'],
         'valor': [500, 300],
         'produto': ['feijao', 'arroz'],
         'qtde': [50, 70],
        }
vendas_df = pd.DataFrame(venda)

### Visualização dos Dados
    - print
    - display

In [3]:
display(vendas_df)

         data  valor produto  qtde
0  15/02/2021    500  feijao    50
1  16/02/2021    300   arroz    70

### Importando arquivos e bases de dados

In [4]:
vendas_df = pd.read_excel("Vendas.xlsx")
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

### Resumos de Visualização de Dados simples e úteis
    - head
    - shape
    - describe

In [6]:
display(vendas_df.head(10))
print(vendas_df.shape)
display(vendas_df.describe())

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248
6,5,2019-01-02,Shopping Barra,Calça,1,170,170
7,6,2019-01-02,Shopping Ibirapuera,Polo Listrado,4,149,596
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105

(93910, 7)

,Código Venda,Data,Quantidade,Valor Unitário,Valor Final
count,93910.00,93910,93910.00,93910.00,93910.00
mean,32464.76,2019-06-16 23:52:28.265360896,2.17,191.73,414.86
min,1.00,2019-01-01 00:00:00,1.00,30.00,30.00
25%,16204.00,2019-03-26 00:00:00,1.00,100.00,156.00
50%,32367.00,2019-06-17 00:00:00,2.00,155.00,274.00
75%,48793.75,2019-09-08 00:00:00,3.00,248.00,524.00
max,65014.00,2019-11-30 00:00:00,5.00,750.00,3750.00
std,18809.01,NaN,1.26,145.22,434.85

### Pegar 1 coluna (e os pd.Series)

In [7]:
produtos = vendas_df [['Produto', 'Quantidade']]
display(produtos)

                 Produto  Quantidade
0         Sapato Estampa           1
1               Camiseta           2
2          Sapato Xadrez           1
3                Relógio           3
4           Chinelo Liso           1
...                  ...         ...
93905     Mochila Xadrez           2
93906  Pulseira Listrado           2
93907     Cueca Listrado           3
93908     Pulseira Linho           5
93909      Casaco Xadrez           4

[93910 rows x 2 columns]

### .loc, um método muito importante
    - Pegar 1 linha
    - Pegar linhas de acordo com alguma condição
    - Pegar linhas e colunas específicas
    - Pegar 1 valor específico

In [22]:
#pegar uma linha
#display(vendas_df.loc[1:5])

#pegar linhas que correspondem a uma condição

#vendas_norte_df = vendas_df.loc[vendas_df['ID Loja'] == 'Norte Shopping']

#display(vendas_norte_df)

# pegar varias linhas e colunas usando loc
#vendas_norte_df = vendas_df.loc[vendas_df ['ID Loja'] == 'Norte Shopping', ["ID Loja", "Produto", "Quantidade", "Valor Final"]]
#display(vendas_norte_df)
#pegar um valor especifico
#quantia = (vendas_df.loc[3, 'Produto'], int(vendas_df.loc[3, 'Quantidade']))
#display(quantia)

('Relógio', 3)

### Adicionar 1 coluna

In [58]:
#a partir de uma coluna que já existe
#vendas_df['Comissão'] = vendas_df['Valor Final'] * 0.05
#display(vendas_df)

#criar uma coluna com valor padrão

#vendas_df.loc[:, "Imposto"] = 0

vendas_df.loc[:, "Imposto"] = 0

display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,Imposto
0,1,2019-01-01 00:00:00,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90,0
1,1,2019-01-01 00:00:00,Iguatemi Esplanada,Camiseta,2,180,360,18.00,0
2,1,2019-01-01 00:00:00,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40,0
3,2,2019-01-02 00:00:00,Norte Shopping,Relógio,3,200,600,30.00,0
4,2,2019-01-02 00:00:00,Norte Shopping,Chinelo Liso,1,71,71,3.55,0
...,...,...,...,...,...,...,...,...,...
93905,65012,2019-11-30 00:00:00,Shopping Vila Velha,Mochila Xadrez,2,283,566,28.30,0
93906,65013,2019-11-30 00:00:00,Ribeirão Shopping,Pulseira Listrado,2,79,158,7.90,0
93907,65013,2019-11-30 00:00:00,Ribeirão Shopping,Cueca Listrado,3,67,201,10.05,0
93908,65014,2019-11-30 00:00:00,Shopping Morumbi,Pulseira Linho,5,114,570,28.50,0
93909,65014,2019-11-30 00:00:00,Shopping Morumbi,Casaco Xadrez,4,259,1036,51.80,0

### Adicionar 1 linha
    - Linhas de um complemento da base de dados

In [8]:
vendas_dez_df = pd.read_excel("Vendas - Dez.xlsx")

vendas_df = pd.concat([vendas_df, vendas_dez_df], ignore_index = True)
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Juros
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,0.00
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,0.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,0.00
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,0.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,0.00
...,...,...,...,...,...,...,...,...
122261,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN
122262,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN
122263,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN
122264,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN
122265,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN

### Excluir linhas e colunas

In [ ]:
vendas_df = vendas_df.drop("Juros", axis=1)
display(vendas_df)
#eixo 0 é a linha, eixo 1 é a coluna, axis = 0

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
122261,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
122262,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
122263,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
122264,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
122265,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

### Valores Vazios
    - Deletar linhas/colunas vazias
    - Deletar linhas que possuem valores vazios
    - Preencher valores vazios (média e último valor)

In [ ]:
#deletar linhas e colunas completamente vazias
#vendas_df = vendas_df.dropna(how="all", axis=1)
#display(vendas_df)

#deletar linhas e colunas com qualquer linha ou coluna vazias
#vendas_df = vendas_df.dropna()
#display(vendas_df)

#preencher valores vazios com a média ou último valor
#preencher com a média da coluna=>
vendas_df["Valor Final"] = vendas_df["Valor Final"].fillna(vendas_df["Valor Final"].mean)
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
122261,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
122262,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
122263,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
122264,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
122265,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

### Calcular Indicadores
    - Groupby
    - Value Counts

### Mesclar 2 dataframes (Procurar informações de um dataframe em outro)

### Como continuar aprendendo?

### Minicurso Gratuito de Análise de Dados com Python na Descrição